name: Update Tags
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment that will be updated with new image tag"
      service:
        required: true
        type: string
        description: "Service that will be updated with new image tag"
      tag:
        required: true
        type: string
        description: "Image tag"

jobs:
  promote-to-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # Clone Repository
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ secrets.token }}

    - name: Install yq
      id: setup-yq
      uses: shiipou/setup-yq-action@v2.2.0

    - name: Update Tags
      run: |
        # change tag with yq
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add services
        git commit -m "AUTO: Bump ${{ inputs.service }} image tag to ${{ inputs.tag }} for env ${{ inputs.environment }}"
        git push
