on:
  workflow_call:
    inputs:
      ECR_REPOSITORY:
        required: true
        type: string
      tag:
        required: true
        type: string
        description: "Image tag"
      role-to-assume:
        required: true
        type: string
      DOJO_URL:
        required: false
        type: string
      runner:
        required: false
        type: string
        default: "ubuntu-22.04"
    secrets:
      AUTH_HEADER:
        description: 'Header used to authenticate in Defect Dojo'
        required: false

jobs:
  build:
    name: Build Image and Push to ECR
    permissions:
      id-token: write
      contents: write
    env:
      ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
      DOJO_URL: ${{ inputs.DOJO_URL }}
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: us-east-1
          role-to-assume: ${{ inputs.role-to-assume }}
          role-session-name: GithubActionsSession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Trivy vulnerability Scan and Import DefectDojo
        run: |
          #Install Trivy
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.45.1

          trivy image  --format json --exit-code  0 --ignore-unfixed --vuln-type  os,library --severity  CRITICAL,HIGH --output  ./results.json --timeout  20m0s  "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{inputs.tag}}"

          #Import Scan in Defect Dojo
          #Date environment variables
          YEAR=`date +%Y`
          MONTH=`date +%B`
          SCAN_EXEC_DATE=`date +%Y-%m-%d`

          curl -X 'POST' \
            "${{env.DOJO_URL}}" \
            -H 'accept: application/json' \
            -H "Authorization: Token ${{ secrets.AUTH_HEADER }}" \
            -H 'Content-Type: multipart/form-data' \
            -H 'X-CSRFTOKEN: mycsrftoken' \
            -F 'product_type_name=' \
            -F 'active=true' \
            -F 'endpoint_to_add=' \
            -F 'verified=true' \
            -F 'close_old_findings=true' \
            -F 'test_title=' \
            -F "engagement_name=$YEAR $MONTH Security Report" \
            -F 'build_id=' \
            -F 'deduplication_on_engagement=true' \
            -F 'push_to_jira=false' \
            -F 'minimum_severity=Info' \
            -F 'close_old_findings_product_scope=false' \
            -F "scan_date=$SCAN_EXEC_DATE" \
            -F 'create_finding_groups_for_all_findings=true' \
            -F 'engagement_end_date=' \
            -F 'environment=Development' \
            -F "service=${{env.ECR_REPOSITORY}}" \
            -F 'commit_hash=' \
            -F 'group_by=finding_title' \
            -F 'version=' \
            -F "tags=${{env.ECR_REPOSITORY}}" \
            -F 'api_scan_configuration=' \
            -F 'product_name=Ubix' \
            -F "file=@results.json;type=application/json" \
            -F 'auto_create_context=' \
            -F 'lead=' \
            -F 'scan_type=Trivy Scan' \
            -F 'branch_tag=' \
            -F 'source_code_management_uri=' \
            -F 'engagement='
