name: Verify Branch and Tag
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment to promote to"
    # outputs: 
    #   count-diff: ${{ jobs.github-ref-verify-on-promote.outputs.count-diff }}


jobs:
  github-ref-verify-on-promote:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    outputs: 
      count-diff: ${{ steps.cdc.outputs.commit-difference-count }}
    steps:
      - name: Get commit difference between source and base branch
        id: cdc
        uses: jessicalostinspace/commit-difference-action@v1.0.0
        if: ${{ inputs.environment == 'new-dev'}}
        with:
          base-branch: ${{ env.BRANCH_NAME }}
          secondary-branch: ${{ github.event.repository.default_branch }}

      - name: Check if commit difference is not 0 
        if: ${{ steps.cdc.outputs.commit-difference-count != 0 }} && ${{ inputs.environment == 'new-dev'}}
        run: | 
         echo "Your feature branch is not up-to-date. Please update it before proceeding. Aborting..." &&
         gh run cancel

      - name: Check if branch is main or master for stg
        if: ${{ inputs.environment == 'stg' }}
        run: |
          if [[ "${{ github.ref_name }}" != "main" ]] && [[ "${{ github.ref_name }}" != "master" ]]; then
            echo "Error: Deployment to 'stg' environment is only allowed from 'main' or 'master' branch."
            exit 1
          fi

      - name: Check if branch name is a valid release tag for prd
        if: ${{ inputs.environment == 'prd' }}
        run: |
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Deployment to 'prd' environment requires a valid release tag (vX.X.X)."
            exit 1
          fi

