name: Update Tags
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment that will be updated with new image tag"
      service:
        required: true
        type: string
        description: "Service that will be updated with new image tag"
      tag:
        required: true
        type: string
        description: "Image tag"
      values-path:
        required: true
        type: string
      tag-path:
        required: false
        type: string
        default: "deployment.image.tag"
      repository:
        required: false
        type: string
        default: "Ubix/ubix-deployments"
      cloudspace_account:
        required: false
        type: string
        default: ''
    secrets:
      token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:
  promote-to-env:
    runs-on: ubuntu-latest
    steps:
      # Clone Repository
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ secrets.token }}
        ref: main

    - name: Install yq
      id: setup-yq
      uses: shiipou/setup-yq-action@v2.2.0

    - name: Update single Cloudspace Account Tag
      if: ${{ inputs.cloudspace_account != '' }}
      run: |
        # change tag with yq
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        yq -i ".${{inputs.service}}.${{inputs.tag-path}} = \"${{inputs.tag}}\"" "cloudspace/overlays/${{ inputs.environment }}/${{ inputs.cloudspace_account }}/${{ inputs.values-path }}/values.yaml"
        git add "cloudspace/overlays/${{ inputs.environment }}/${{ inputs.cloudspace_account }}/${{ inputs.values-path }}/values.yaml"
        git commit -m "AUTO: Bump ${{ inputs.service }} image tag to ${{ inputs.tag }} for ${{ inputs.environment }} cloudspace_account ${{ inputs.cloudspace_account }}"
        git push
        
    - name: Update all Cloudspace Accounts Tags
      if: ${{ inputs.cloudspace_account == '' }}
      run: |
        # change tag with yq
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        find cloudspace/overlays/"${{ inputs.environment }}" -type f -path "*/${{ inputs.values-path }}/values.yaml" -exec yq -i ".${{inputs.service}}.${{inputs.tag-path}} = \"${{inputs.tag}}\"" {} \;
        git add "cloudspace/overlays/"${{ inputs.environment }}/"
        git commit -m "AUTO: Bump ${{ inputs.service }} image tag to ${{ inputs.tag }} for all ${{ inputs.environment }} cloudspace accounts"
        git push
