name: Cloudspace Update Tags
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment that will be updated with new image tag"
      service:
        required: true
        type: string
        description: "Service that will be updated with new image tag"
      tag:
        required: true
        type: string
        description: "Image tag"
      values-path:
        required: true
        type: string
      base-path:
        required: true
        type: string
      tag-path:
        required: false
        type: string
        default: "deployment.image.tag"
      repository:
        required: false
        type: string
        default: "Ubix/ubix-deployments"
      cloudspace_account:
        type: string
        required: false
        default: ''
    secrets:
      token:
        description: 'A token passed from the caller workflow'
        required: false

jobs:
  promote-to-env:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
    steps:
      # Clone Repository
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.repository }}
        token: ${{ secrets.token }}
        ref: main

    - name: Install yq
      id: setup-yq
      uses: shiipou/setup-yq-action@v2.2.0
        
    - name: Update Cloudspace Account Tags
      run: |
        # change tag with yq
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        find "${{ inputs.base-path }}" -type f -path "*/${{ inputs.values-path }}/values.yaml" -exec yq -i ".${{inputs.service}}.${{inputs.tag-path}} = \"${{inputs.tag}}\"" {} \;
        git add "${{ inputs.base-path }}/"
        git commit -m "AUTO: Bump ${{ inputs.service }} image tag to ${{ inputs.tag }} for ${{ inputs.environment }} ${{ inputs.cloudspace_account }}"
        git push
