name: Verify Branch and Tag
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment to promote to"

jobs:
  github-ref-verify-on-promote:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    outputs:
      count-diff: ${{ steps.cdc.outputs.commitDiffCount }}
    steps:
      - name: Checkout Git Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit difference between source and base branch
        id: cdc
        if: ${{ inputs.environment == 'new-dev'}}
        env:
          FEATURE_BRANCH: ${{ env.BRANCH_NAME }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          commits_behind=$(git rev-list --count origin/${{ env.FEATURE_BRANCH }}..origin/${{ env.BASE_BRANCH }})
          echo "$commits_behind"
          echo "commitDiffCount=$commits_behind" >> $GITHUB_OUTPUT

      - name: Check if commit difference is not 0
        if: ${{ steps.cdc.outputs.commitDiffCount != 0 }} && ${{ inputs.environment == 'new-dev'}}
        run: |
          echo "Your feature branch is not up-to-date. It is behind by ${{ steps.cdc.outputs.commitDiffCount }} commits. Please update it before proceeding. Aborting..." &&
          exit 1

      - name: Check if branch is main or master for stg
        if: ${{ inputs.environment == 'stg' }}
        run: |
          if [[ "${{ github.ref_name }}" != "main" ]] && [[ "${{ github.ref_name }}" != "master" ]]; then
            echo "Error: Deployment to 'stg' environment is only allowed from 'main' or 'master' branch."
            exit 1
          fi

      - name: Check if branch name is a valid release tag for prd
        if: ${{ inputs.environment == 'prd' }}
        run: |
          if [[ ! "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Deployment to 'prd' environment requires a valid release tag (vX.X.X)."
            exit 1
          fi
